# TC3-40 — Catálogo de Variáveis e Fontes de Dados Adicionais

**Objetivo:** documentar as bases complementares efetivamente disponíveis, suas tabelas/abas e colunas, padronizando metadados para apoiar a decisão sobre quais fontes serão utilizadas no projeto.

**Escopo:** inventário de arquivos, tabelas/abas, colunas, siglas, descrições, tipos, granularidade, cobertura e limitações observadas. A base consolidada preparada por integrante do grupo deve ser descrita como produto de uma etapa de seleção/filtro, sem presumir que seus critérios estejam validados até serem documentados.

**Fora do escopo:** integração final entre fontes, definição definitiva das features, imputação de valores e modelagem. A `ml_aluno` permanece como base principal e sua auditoria fica no TC3-38.

> Execute a partir da raiz do repositório. Os sete arquivos exibidos no repositório ficam juntos em `dados/fontes_originais/complementar`; o notebook procura os nomes específicos nessa pasta. A base consolidada de Mauricio será identificada separadamente, caso esteja em `dados/fontes_originais/principal` ou `dados/fontes_originais/complementar`. Arquivos não encontrados são registrados como pendentes; o notebook não presume que estejam disponíveis.

## 1. Bibliotecas e localização dos arquivos

## Inicialização independente

Esta célula reproduz a configuração compartilhada do notebook principal. Ela prepara ambiente, caminhos e funções comuns sem alterar a lógica canônica desta etapa.

In [1]:
# =============================================================================
# CONFIGURAÇÕES PARA RODAR O NOTEBOOK
# Execute esta célula primeiro. Esta política não altera a metodologia do fluxo.
# =============================================================================
import os
import sys
import gc
import ctypes
import polars as pl
from datetime import datetime, timezone

# Opções do usuário
PERFIL_RECURSOS = "auto"       # auto | baixo | medio | normal | alto
LIMITE_RAM_PERCENTUAL = None    # None = automático; ou inteiro entre 50 e 90
MAX_THREADS = None              # None = automático; ou inteiro >= 1
USAR_GPU = os.getenv("TC3_USAR_GPU", "1").strip().lower() in {"1", "true", "sim", "yes"}                 # requer WSL2 + RAPIDS/cuML + kernel tc3-gpu

REUTILIZAR_ARTEFATOS = False  # False reconstrói; True aceita caches válidos
SALVAR_ARTEFATOS = True       # False usa somente área temporária da sessão


# Protocolo metodologico compartilhado por todas as fases e modelos.
SEED_GLOBAL = 42
EXECUTAR_SHAP = os.getenv("TC3_EXECUTAR_SHAP", "0").strip().lower() in {"1", "true", "sim", "yes"}
AMOSTRA_SHAP = max(20, int(os.getenv("TC3_AMOSTRA_SHAP", "100")))
AMOSTRA_BACKGROUND_SHAP = max(20, int(os.getenv("TC3_BACKGROUND_SHAP", "50")))
CHAVE_GRUPO_GLOBAL = "chave_escola_ano"
N_SPLITS_CV_GLOBAL = 3
N_ITER_BUSCA_GLOBAL = 10
LIMIAR_CLASSIFICACAO_GLOBAL = 0.50
REPETICOES_PERMUTACAO_GLOBAL = 5
REPETICOES_BOOTSTRAP_GLOBAL = 200

N_JOBS_MODELAGEM_GLOBAL = 1
N_SPLITS_HOLDOUT_GLOBAL = 1
SCORING_PRINCIPAL_GLOBAL = "roc_auc"
VERBOSE_BUSCA_GLOBAL = 2
ERRO_BUSCA_GLOBAL = "raise"
RETORNAR_SCORE_TREINO_GLOBAL = True

# Contrato comum de pre-processamento dos modelos.
IMPUTACAO_NUMERICA_GLOBAL = "median"
IMPUTACAO_CATEGORICA_GLOBAL = "most_frequent"
ONE_HOT_DESCONHECIDO_GLOBAL = "ignore"
ONE_HOT_SPARSO_GLOBAL = False  # matriz densa: evita fallback dos modelos para CPU
SPARSE_THRESHOLD_GLOBAL = 0.0
ESCALONADOR_CENTRALIZAR_GLOBAL = False


# Percentuais de amostragem (0 < valor <= 1). Alterar aqui afeta todo o notebook.
# O teste final permanece integral (100%); as amostras menores servem apenas ao
# desenvolvimento, comparacao de modelos e interpretabilidade.
FRACOES_AMOSTRAGEM = {
    "eda_correlacao": 0.05,
    "validacao_preparacao": 0.02,
    "fase5_modelos": 0.10,
    "fase5_knn": 0.02,  # KNN tem custo de memoria e predicao maior.
    "fase6_desenvolvimento": 0.12,
    "fase6_validacao_interna": 0.25,
    "fase7_desenvolvimento": 1.00,
    "fase7_teste": 1.00,
    "interpretacao": 0.035,
    "bootstrap": 0.17,
}

for _nome, _fracao in FRACOES_AMOSTRAGEM.items():
    if not 0 < _fracao <= 1:
        raise ValueError(f"Fracao invalida em FRACOES_AMOSTRAGEM[{_nome!r}]: {_fracao}")


def tamanho_por_fracao(total, fracao):
    """Converte uma proporcao em quantidade reproduzivel, sem exceder o total."""
    if total < 1:
        raise ValueError("Nao e possivel amostrar uma particao vazia.")
    return min(total, max(1, round(total * fracao)))


def materializar_split_percentual(dados, contrato, nome_split, fracao, seed, materializador):
    """Materializa uma fracao de um split e informa claramente o universo usado."""
    import polars as pl

    coluna_split = contrato["controle_split"]
    total = (
        dados.filter(pl.col(coluna_split) == nome_split)
        .select(pl.len().alias("total"))
        .collect()
        .item()
    )
    quantidade = tamanho_por_fracao(total, fracao)
    X, y = materializador(dados, contrato, nome_split, limit=quantidade, seed=seed)
    print(f"{nome_split}: {quantidade:,}/{total:,} registros ({fracao:.1%})")
    return X, y


def _estado_memoria_sistema():
    """Retorna RAM total e disponível em bytes."""
    valores = {}
    try:
        with open("/proc/meminfo", encoding="utf-8") as arquivo:
            for linha in arquivo:
                chave, valor = linha.split(":", 1)
                valores[chave] = int(valor.strip().split()[0]) * 1024
        return valores["MemTotal"], valores.get("MemAvailable", valores.get("MemFree", 0))
    except (OSError, KeyError, ValueError):
        try:
            return (
                os.sysconf("SC_PHYS_PAGES") * os.sysconf("SC_PAGE_SIZE"),
                os.sysconf("SC_AVPHYS_PAGES") * os.sysconf("SC_PAGE_SIZE"),
            )
        except (AttributeError, OSError, ValueError):
            return None, None


RAM_TOTAL_BYTES, RAM_DISPONIVEL_BYTES = _estado_memoria_sistema()
RAM_TOTAL_GB = RAM_TOTAL_BYTES / 1024**3 if RAM_TOTAL_BYTES else 0.0
CPUS_LOGICAS = os.cpu_count() or 1

if RAM_TOTAL_GB and RAM_TOTAL_GB <= 4.5:
    _perfil_detectado = "baixo"
elif RAM_TOTAL_GB and RAM_TOTAL_GB <= 8.5:
    _perfil_detectado = "medio"
elif RAM_TOTAL_GB and RAM_TOTAL_GB <= 16.5:
    _perfil_detectado = "normal"
else:
    _perfil_detectado = "alto"

_perfis = {
    "baixo": (60, 1),
    "medio": (70, min(2, CPUS_LOGICAS)),
    "normal": (75, min(4, CPUS_LOGICAS)),
    "alto": (80, min(8, max(1, CPUS_LOGICAS // 2))),
}
PERFIL_ATIVO = _perfil_detectado if PERFIL_RECURSOS == "auto" else PERFIL_RECURSOS.lower()
if PERFIL_ATIVO not in _perfis:
    raise ValueError("PERFIL_RECURSOS deve ser auto, baixo, medio, normal ou alto.")

_limite_perfil, _threads_perfil = _perfis[PERFIL_ATIVO]
LIMITE_RAM_ATIVO = _limite_perfil if LIMITE_RAM_PERCENTUAL is None else int(LIMITE_RAM_PERCENTUAL)
THREADS_MAXIMAS = _threads_perfil if MAX_THREADS is None else int(MAX_THREADS)
if not 50 <= LIMITE_RAM_ATIVO <= 90:
    raise ValueError("LIMITE_RAM_PERCENTUAL deve ficar entre 50 e 90.")
if THREADS_MAXIMAS < 1:
    raise ValueError("MAX_THREADS deve ser pelo menos 1.")
THREADS_MAXIMAS = min(THREADS_MAXIMAS, CPUS_LOGICAS)

# Definido antes de NumPy, Polars, scikit-learn e cuML serem importados.
for _variavel, _valor in {
    "OMP_NUM_THREADS": str(THREADS_MAXIMAS),
    "OPENBLAS_NUM_THREADS": str(THREADS_MAXIMAS),
    "MKL_NUM_THREADS": str(THREADS_MAXIMAS),
    "NUMEXPR_NUM_THREADS": str(THREADS_MAXIMAS),
    "VECLIB_MAXIMUM_THREADS": str(THREADS_MAXIMAS),
    "POLARS_MAX_THREADS": str(THREADS_MAXIMAS),
    "MALLOC_ARENA_MAX": "2",
}.items():
    os.environ[_variavel] = _valor

HISTORICO_RECURSOS = []
_estado_recursos = {"nivel": None, "threads": None, "contexto_threads": None}


def _aplicar_threads(limite):
    """Limita pools BLAS/OpenMP já carregados; Polars usa o limite inicial."""
    limite = max(1, min(int(limite), THREADS_MAXIMAS))
    if _estado_recursos["threads"] == limite:
        return
    anterior = _estado_recursos.get("contexto_threads")
    if anterior is not None:
        try:
            anterior.__exit__(None, None, None)
        except Exception:
            pass
    try:
        from threadpoolctl import threadpool_limits
        contexto = threadpool_limits(limits=limite)
        contexto.__enter__()
    except Exception:
        contexto = None
    _estado_recursos["contexto_threads"] = contexto
    _estado_recursos["threads"] = limite


def _liberar_memoria_global(agressiva=False):
    """Libera caches transitórios sem apagar variáveis usadas pelo fluxo."""
    shell = get_ipython()
    if shell is not None:
        for nome in ("_", "__", "___"):
            shell.user_ns[nome] = None
    gc.collect()
    modulo_cupy = sys.modules.get("cupy")
    if modulo_cupy is not None:
        try:
            modulo_cupy.get_default_memory_pool().free_all_blocks()
            modulo_cupy.get_default_pinned_memory_pool().free_all_blocks()
        except Exception:
            pass
    if agressiva:
        modulo_plt = sys.modules.get("matplotlib.pyplot")
        if modulo_plt is not None:
            try:
                modulo_plt.close("all")
            except Exception:
                pass
        try:
            ctypes.CDLL("libc.so.6").malloc_trim(0)
        except (OSError, AttributeError):
            pass


def _gerenciar_recursos(*_args, **_kwargs):
    """Reduz paralelismo progressivamente e nunca interrompe uma célula."""
    total, disponivel = _estado_memoria_sistema()
    if not total:
        return
    uso = 100.0 * (total - disponivel) / total
    margem = LIMITE_RAM_ATIVO - uso
    if margem > 15:
        nivel, threads, limpar = "normal", THREADS_MAXIMAS, False
    elif margem > 7:
        nivel, threads, limpar = "moderado", max(1, THREADS_MAXIMAS // 2), True
    else:
        nivel, threads, limpar = "conservador", 1, True

    _aplicar_threads(threads)
    if limpar:
        _liberar_memoria_global(agressiva=margem <= 0)

    if nivel != _estado_recursos["nivel"]:
        registro = {
            "instante_utc": datetime.now(timezone.utc).isoformat(),
            "nivel": nivel,
            "threads": threads,
            "ram_usada_percentual": round(uso, 1),
            "ram_disponivel_gb": round(disponivel / 1024**3, 2),
        }
        HISTORICO_RECURSOS.append(registro)
        print(
            f"[recursos] nível={nivel}; threads={threads}; "
            f"RAM usada={uso:.1f}%; livre={disponivel / 1024**3:.1f} GB."
        )
        _estado_recursos["nivel"] = nivel


ipython = get_ipython()
if ipython is not None:
    # Impede callbacks duplicados ao reexecutar a configuração.
    for _atributo in ("_tc3_memory_guard", "_tc3_resource_guard"):
        _guard_anterior = getattr(ipython, _atributo, None)
        if _guard_anterior is not None:
            for _evento, _funcao in _guard_anterior:
                try:
                    ipython.events.unregister(_evento, _funcao)
                except (ValueError, KeyError):
                    pass
    _callbacks_recursos = [
        ("pre_run_cell", _gerenciar_recursos),
        ("post_run_cell", _gerenciar_recursos),
    ]
    for _evento, _funcao in _callbacks_recursos:
        ipython.events.register(_evento, _funcao)
    ipython._tc3_resource_guard = _callbacks_recursos

_gerenciar_recursos()
print(
    "Configuração automática ativa: "
    f"perfil={PERFIL_ATIVO}; RAM={RAM_TOTAL_GB:.1f} GB; CPUs={CPUS_LOGICAS}; "
    f"limite preventivo={LIMITE_RAM_ATIVO}%; threads máximas={THREADS_MAXIMAS}."
)

# Backend GPU: ativado antes de qualquer importação do scikit-learn.
cuda_conda = os.path.join(sys.prefix, "targets", "x86_64-linux")
if os.path.exists(os.path.join(cuda_conda, "include", "cuda.h")):
    os.environ.setdefault("CUDA_PATH", cuda_conda)
if USAR_GPU:
    try:
        from cuml.accel import install
        install(log_level="info")
        import cupy as cp
        dispositivo = cp.cuda.runtime.getDeviceProperties(0)
        nome_gpu = dispositivo["name"].decode() if isinstance(dispositivo["name"], bytes) else str(dispositivo["name"])
        memoria_gpu_gb = cp.cuda.runtime.memGetInfo()[1] / 1024**3
        BACKEND_ML = f"RAPIDS cuML — {nome_gpu} ({memoria_gpu_gb:.1f} GB de VRAM)"
    except Exception as exc:
        raise RuntimeError("GPU/RAPIDS indisponível. Abra no WSL2 e selecione o kernel tc3-gpu.") from exc
else:
    BACKEND_ML = "scikit-learn CPU"
print("Backend de Machine Learning:", BACKEND_ML)

from pathlib import Path
import hashlib
import json
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

def localizar_raiz(inicio: Path) -> Path:
    for candidato in [inicio, *inicio.parents]:
        if (candidato / "dados").is_dir() and (candidato / "notebooks").is_dir():
            return candidato
    raise FileNotFoundError("Execute este notebook dentro do repositório tech_challenge_3.")

PROJECT_ROOT = localizar_raiz(Path.cwd().resolve())
print("Raiz do projeto:", PROJECT_ROOT)


# Contrato único de diretórios. Fontes sempre são lidas da área imutável.
import tempfile

FONTES_ORIGINAIS_DIR = PROJECT_ROOT / "dados" / "fontes_originais"
_TEMP_BASE = PROJECT_ROOT / ".execucao_temporaria"
_TEMP_BASE.mkdir(parents=True, exist_ok=True)
if SALVAR_ARTEFATOS:
    RAIZ_ARTEFATOS = PROJECT_ROOT
    _DIRETORIO_TEMPORARIO = None
else:
    _DIRETORIO_TEMPORARIO = tempfile.TemporaryDirectory(prefix="tc3_", dir=_TEMP_BASE)
    RAIZ_ARTEFATOS = Path(_DIRETORIO_TEMPORARIO.name)

DADOS_PROCESSADOS_DIR = RAIZ_ARTEFATOS / "dados" / "dados_processados"
DADOS_ANALITICOS_DIR = RAIZ_ARTEFATOS / "dados" / "dados_analiticos"
RESULTADOS_DIR = RAIZ_ARTEFATOS / "resultados"
RESULTADOS_FIGURAS_DIR = RESULTADOS_DIR / "figuras"
RESULTADOS_TABELAS_DIR = RESULTADOS_DIR / "tabelas"
RESULTADOS_METRICAS_DIR = RESULTADOS_DIR / "metricas"
RESULTADOS_RELATORIOS_DIR = RESULTADOS_DIR / "relatorios"
MODELOS_DIR = RAIZ_ARTEFATOS / "modelos"

for _diretorio_saida in (
    DADOS_PROCESSADOS_DIR, DADOS_ANALITICOS_DIR, RESULTADOS_FIGURAS_DIR,
    RESULTADOS_TABELAS_DIR, RESULTADOS_METRICAS_DIR,
    RESULTADOS_RELATORIOS_DIR, MODELOS_DIR,
):
    _diretorio_saida.mkdir(parents=True, exist_ok=True)

def deve_recalcular(caminho):
    """True quando o cache deve ser ignorado ou ainda não existe."""
    return not REUTILIZAR_ARTEFATOS or not Path(caminho).exists()


def publicar_parquet_particionado(frame, destino, *, particionar_por):
    """Publica partições sequencialmente e troca o diretório de forma atômica.

    O ``write_parquet(partition_by=...)`` do Polars prepara várias partições em
    paralelo e pode duplicar o pico de RAM de bases já materializadas. Esta
    implementação mantém apenas uma partição adicional em memória por vez.
    """
    import gc
    import shutil

    destino = Path(destino)
    temporario = destino.with_name(destino.name + "__publicacao_tmp")
    anterior = destino.with_name(destino.name + "__publicacao_anterior")
    for caminho in (temporario, anterior):
        if caminho.exists():
            shutil.rmtree(caminho)
    temporario.mkdir(parents=True, exist_ok=True)

    lazy = frame if isinstance(frame, pl.LazyFrame) else frame.lazy()
    schema = lazy.collect_schema()
    if particionar_por not in schema.names():
        raise ValueError(f"Coluna de particionamento ausente: {particionar_por}")

    valores = (
        lazy.select(pl.col(particionar_por).unique())
        .collect(engine="streaming")
        .get_column(particionar_por)
        .to_list()
    )
    valores = sorted(valores, key=lambda valor: (valor is None, str(valor)))
    if not valores:
        raise RuntimeError("Não há valores para particionar a publicação.")

    arquivos_novos = []
    for indice, valor in enumerate(valores):
        valor_hive = "__HIVE_DEFAULT_PARTITION__" if valor is None else str(valor)
        if any(separador in valor_hive for separador in ("/", "\\")):
            raise ValueError(f"Valor de partição inválido: {valor_hive!r}")
        diretorio_particao = temporario / f"{particionar_por}={valor_hive}"
        diretorio_particao.mkdir(parents=True, exist_ok=True)
        arquivo = diretorio_particao / f"part-{indice:05d}.parquet"
        predicado = pl.col(particionar_por).is_null() if valor is None else pl.col(particionar_por) == pl.lit(valor)
        lazy.filter(predicado).sink_parquet(
            arquivo,
            compression="zstd",
            statistics=True,
            row_group_size=100_000,
            mkdir=True,
            engine="streaming",
        )
        if not arquivo.is_file() or arquivo.stat().st_size == 0:
            raise RuntimeError(f"Partição não foi gravada corretamente: {arquivo}")
        arquivos_novos.append(arquivo)
        gc.collect()

    if destino.exists():
        destino.replace(anterior)
    try:
        try:
            temporario.replace(destino)
        except OSError:
            # Volumes Docker montados do Windows podem bloquear rename de diretórios.
            # O fallback copia a publicação pronta e remove a área temporária.
            shutil.copytree(temporario, destino)
            shutil.rmtree(temporario)
    except Exception:
        if destino.exists():
            shutil.rmtree(destino)
        if anterior.exists():
            anterior.replace(destino)
        raise
    if anterior.exists():
        shutil.rmtree(anterior)
    return len(arquivos_novos)


def salvar_figura_eda(figura, nome):
    """Exporta uma figura exploratória sem alterar sua exibição no notebook."""
    destino = RESULTADOS_FIGURAS_DIR / "fluxo_exploratorio" / nome
    destino.parent.mkdir(parents=True, exist_ok=True)
    figura.savefig(destino, dpi=180, bbox_inches="tight")
    return destino

print("Fontes originais:", FONTES_ORIGINAIS_DIR)
print("Destino dos artefatos:", RAIZ_ARTEFATOS)
print("Reutilizar artefatos:", REUTILIZAR_ARTEFATOS, "| Salvar:", SALVAR_ARTEFATOS)

# Imports compartilhados que, no fluxo completo, são carregados por etapas anteriores.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display

[recursos] nível=normal; threads=4; RAM usada=24.7%; livre=11.6 GB.
Configuração automática ativa: perfil=normal; RAM=15.5 GB; CPUs=20; limite preventivo=75%; threads máximas=4.
[cuml.accel] Accelerator installed.
Backend de Machine Learning: RAPIDS cuML — NVIDIA GeForce RTX 3050 6GB Laptop GPU (6.0 GB de VRAM)
Raiz do projeto: /workspace
Fontes originais: /workspace/dados/fontes_originais
Destino dos artefatos: /workspace
Reutilizar artefatos: False | Salvar: True

In [2]:
from pathlib import Path
import zipfile
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display

plt.rcParams["figure.figsize"] = (9, 4)

# Localiza a raiz do repositório e a pasta única das bases complementares.
CWD = Path.cwd().resolve()
PROJECT_ROOT = next(
    (p for p in [CWD, *CWD.parents] if (p / ".git").exists() and (p / "dados").is_dir()),
    None,
)
if PROJECT_ROOT is None:
    PROJECT_ROOT = next(
        (p for p in [CWD, *CWD.parents] if (p / "dados" / "fontes_originais" / "complementar").is_dir()),
        CWD,
    )

DATA_COMPLEMENTAR = PROJECT_ROOT / "dados" / "fontes_originais" / "complementar"
DATA_PRINCIPAL = PROJECT_ROOT / "dados" / "fontes_originais" / "principal"


def localizar_arquivo(padroes, pasta=DATA_COMPLEMENTAR):
    if isinstance(padroes, str):
        padroes = [padroes]
    encontrados = []
    if pasta.exists():
        for padrao in padroes:
            encontrados.extend(pasta.glob(padrao))
    encontrados = [x for x in encontrados if x.is_file()]
    if encontrados:
        return sorted(set(encontrados), key=lambda x: str(x).lower())[0]
    return None

# Nomes/padrões alinhados aos arquivos que aparecem em dados/fontes_originais/complementar no GitHub.
# Os padrões aceitam variações apenas nos trechos truncados/acentuação, sem procurar fora da pasta.
arquivos_configurados = {
    "Censo Escolar 2023 (microdados ZIP)": ["microdados_ed_basica_2023.zip"],
    "INSE 2023 — escolas": ["INSE_2023_escolas.xlsx", "INSE_2023_escolas*.xlsx"],
    "Bolsa Família": ["base_dados_bolsa_familia_2023_2024.csv"],
    "Indicador municipal FUNDEB": ["base_dados_fundeb_indicador_municipal_2023_2024.csv", "base_dados_fundeb_indicador_municipal_2023_2024*.csv"],
    "PIB municipal": ["base_de_dados_PIB_Municipios_2022_2023.csv", "base_de_dados_PIB_Municipios*.csv"],
    "Receitas orçamentárias municipais": ["base_de_dados_municipio_receitas_orcamentarias_2023_2024.csv", "base_de_dados_municipio_receitas_orcamentarias_20*.csv"],
    "Dicionário de dados da educação básica": ["dicionário_dados_educação_básica.xlsx", "dicionario_dados_educacao_basica.xlsx", "dicionário_dados_educação_básica*.xlsx", "dicionario_dados_educacao_basica*.xlsx"],
}
localizados = {nome: localizar_arquivo(padroes) for nome, padroes in arquivos_configurados.items()}

# A base consolidada do Mauricio pode ter outro nome. Procuramos arquivos candidatos
# no diretório de dados, mas não presumimos que qualquer arquivo com 'consolid' seja o correto.
consolidados_encontrados = []
for pasta in [DATA_PRINCIPAL, DATA_COMPLEMENTAR]:
    if pasta.exists():
        consolidados_encontrados.extend(
            p for p in pasta.rglob("*")
            if p.is_file() and "consolid" in p.name.lower()
            and p.suffix.lower() in {".csv", ".parquet", ".xlsx", ".xls", ".zip"}
        )
consolidados_encontrados = sorted(set(consolidados_encontrados))

inventario_arquivos = pl.DataFrame([
    {"Base/arquivo": nome,
     "Encontrado em dados/fontes_originais/complementar": caminho is not None,
     "Caminho identificado": str(caminho.relative_to(PROJECT_ROOT)) if caminho else "Não localizado; conferir nome/caminho"}
    for nome, caminho in localizados.items()
])
print(f"Raiz do projeto: {PROJECT_ROOT}")
print(f"Pasta complementar: {DATA_COMPLEMENTAR}")
display(inventario_arquivos)
print("\nArquivos candidatos à base consolidada (confirmar com Mauricio):")
if consolidados_encontrados:
    display(pl.DataFrame([
        {"Arquivo candidato": p.name, "Caminho": str(p.relative_to(PROJECT_ROOT))}
        for p in consolidados_encontrados
    ]))
else:
    display(pl.DataFrame([
        {"Arquivo candidato": "Não localizado automaticamente", "Caminho": "Confirmar nome/caminho com Mauricio"}
    ]))

Raiz do projeto: /workspace
Pasta complementar: /workspace/dados/fontes_originais/complementar

shape: (7, 3)
┌────────────────────────────┬──────────────────────────────────┬──────────────────────────────────┐
│ Base/arquivo               ┆ Encontrado em dados/fontes_ori…  ┆ Caminho identificado             │
│ ---                        ┆ ---                              ┆ ---                              │
│ str                        ┆ bool                             ┆ str                              │
╞════════════════════════════╪══════════════════════════════════╪══════════════════════════════════╡
│ Censo Escolar 2023         ┆ true                             ┆ dados/fontes_originais/complem…  │
│ (microdados…               ┆                                  ┆                                  │
│ INSE 2023 — escolas        ┆ true                             ┆ dados/fontes_originais/complem…  │
│ Bolsa Família              ┆ true                             ┆ dados/fontes_originais/complem…  │
│ Indicador municipal FUNDEB ┆ true                             ┆ dados/fontes_originais/complem…  │
│ PIB municipal              ┆ true                             ┆ dados/fontes_originais/complem…  │
│ Receitas orçamentárias     ┆ true                             ┆ dados/fontes_originais/complem…  │
│ municip…                   ┆                                  ┆                                  │
│ Dicionário de dados da     ┆ true                             ┆ dados/fontes_originais/complem…  │
│ educaçã…                   ┆                                  ┆                                  │
└────────────────────────────┴──────────────────────────────────┴──────────────────────────────────┘

Arquivos candidatos à base consolidada (confirmar com Mauricio):

shape: (1, 2)
┌────────────────────────────────┬─────────────────────────────────┐
│ Arquivo candidato              ┆ Caminho                         │
│ ---                            ┆ ---                             │
│ str                            ┆ str                             │
╞════════════════════════════════╪═════════════════════════════════╡
│ Não localizado automaticamente ┆ Confirmar nome/caminho com Mau… │
└────────────────────────────────┴─────────────────────────────────┘

## 2. Inventário dos microdados do Censo Escolar 2023

O arquivo `microdados_ed_basica_2023.zip` é o pacote de microdados do Censo Escolar 2023. Ele é diferente do `dicionário_dados_educação_básica.xlsx`, que contém documentação das variáveis. A célula seguinte verifica se o ZIP foi localizado e lista seus arquivos internos; a seção de inventário padronizado tenta ler apenas os cabeçalhos dos CSVs, sem carregar a base completa na memória.

In [3]:
caminho_censo_zip = localizados.get("Censo Escolar 2023 (microdados ZIP)")
arquivos_internos_censo = []
if caminho_censo_zip:
    try:
        with zipfile.ZipFile(caminho_censo_zip, "r") as zf:
            arquivos_internos_censo = [n for n in zf.namelist() if not n.endswith("/")]
        print("Microdados do Censo Escolar localizados:", caminho_censo_zip.relative_to(PROJECT_ROOT))
        print("Quantidade de arquivos dentro do ZIP:", len(arquivos_internos_censo))
        display(pl.DataFrame({"Arquivo interno": arquivos_internos_censo}))
    except Exception as exc:
        print("O ZIP foi localizado, mas não foi possível listar seu conteúdo:", exc)
else:
    print("Microdados do Censo Escolar 2023 não localizados em dados/fontes_originais/complementar.")

if localizados.get("Dicionário de dados da educação básica"):
    print("Dicionário da educação básica localizado:", localizados["Dicionário de dados da educação básica"].name)

Microdados do Censo Escolar localizados: dados/fontes_originais/complementar/microdados_ed_basica_2023.zip
Quantidade de arquivos dentro do ZIP: 1

shape: (1, 1)
┌───────────────────────────────┐
│ Arquivo interno               │
│ ---                           │
│ str                           │
╞═══════════════════════════════╡
│ microdados_ed_basica_2023.csv │
└───────────────────────────────┘

Dicionário da educação básica localizado: dicionário_dados_educação_básica.xlsx

**Nota metodológica:** o ZIP contém os microdados do Censo Escolar; o arquivo Excel do dicionário é documentação complementar. O inventário das colunas dos microdados será feito a partir dos cabeçalhos dos arquivos internos do ZIP, quando a estrutura permitir leitura sem extração completa. O dicionário não substitui os dados e as descrições só serão associadas quando houver correspondência confirmada entre os nomes das variáveis.

## 3. Inventário das planilhas INSE 2023

In [4]:
def ler_excel_seguro(caminho):
    try:
        planilhas = pl.read_excel(caminho, sheet_id=0, engine="openpyxl")
        if isinstance(planilhas, pl.DataFrame):
            planilhas = {"Sheet1": planilhas}
        resumo = [
            {"Arquivo": caminho.name, "Aba": aba, "Registros": frame.height, "Colunas": frame.width}
            for aba, frame in planilhas.items()
        ]
        return resumo, planilhas
    except Exception as exc:
        return [{"Arquivo": caminho.name, "Aba": "ERRO DE LEITURA", "Registros": None, "Colunas": None, "Erro": str(exc)}], {}

resumos_inse, amostras_inse = [], {}
for nome in ["INSE 2023 — escolas"]:
    caminho = localizados[nome]
    if caminho:
        resumo, amostras = ler_excel_seguro(caminho)
        resumos_inse.extend(resumo); amostras_inse[nome] = amostras
display(pl.DataFrame(resumos_inse))
if "INSE 2023 — escolas" in amostras_inse:
    for aba, df_amostra in amostras_inse["INSE 2023 — escolas"].items():
        print(f"Amostra — INSE escolas / aba: {aba}"); display(df_amostra.head()); print("Colunas:", df_amostra.columns); break

shape: (2, 4)
┌────────────────────────┬───────────────┬───────────┬─────────┐
│ Arquivo                ┆ Aba           ┆ Registros ┆ Colunas │
│ ---                    ┆ ---           ┆ ---       ┆ ---     │
│ str                    ┆ str           ┆ i64       ┆ i64     │
╞════════════════════════╪═══════════════╪═══════════╪═════════╡
│ INSE_2023_escolas.xlsx ┆ INSE_ESC_2023 ┆ 69756     ┆ 22      │
│ INSE_2023_escolas.xlsx ┆ Dicionário    ┆ 22        ┆ 2       │
└────────────────────────┴───────────────┴───────────┴─────────┘

Amostra — INSE escolas / aba: INSE_ESC_2023

shape: (5, 22)
┌─────────────┬───────┬───────┬──────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ NU_ANO_SAEB ┆ CO_UF ┆ SG_UF ┆ NO_UF    ┆ … ┆ PC_NIVEL_5 ┆ PC_NIVEL_6 ┆ PC_NIVEL_7 ┆ PC_NIVEL_8 │
│ ---         ┆ ---   ┆ ---   ┆ ---      ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ i64         ┆ i64   ┆ str   ┆ str      ┆   ┆ f64        ┆ f64        ┆ f64        ┆ f64        │
╞═════════════╪═══════╪═══════╪══════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 2023        ┆ 11    ┆ RO    ┆ Rondônia ┆ … ┆ 25.0       ┆ null       ┆ null       ┆ null       │
│ 2023        ┆ 11    ┆ RO    ┆ Rondônia ┆ … ┆ 50.49      ┆ null       ┆ null       ┆ null       │
│ 2023        ┆ 11    ┆ RO    ┆ Rondônia ┆ … ┆ 23.92      ┆ 13.2       ┆ 7.7        ┆ 0.9        │
│ 2023        ┆ 11    ┆ RO    ┆ Rondônia ┆ … ┆ 18.72      ┆ 10.43      ┆ 10.43      ┆ null       │
│ 2023        ┆ 11    ┆ RO    ┆ Rondônia ┆ … ┆ 24.04      ┆ 16.09      ┆ 17.35      ┆ 1.56       │
└─────────────┴───────┴───────┴──────────┴───┴────────────┴────────────┴────────────┴────────────┘

Colunas: ['NU_ANO_SAEB', 'CO_UF', 'SG_UF', 'NO_UF', 'CO_MUNICIPIO', 'NO_MUNICIPIO', 'ID_ESCOLA', 'NO_ESCOLA', 'TP_TIPO_REDE', 'TP_LOCALIZACAO', 'TP_CAPITAL', 'QTD_ALUNOS_INSE', 'MEDIA_INSE', 'INSE_CLASSIFICACAO', 'PC_NIVEL_1', 'PC_NIVEL_2', 'PC_NIVEL_3', 'PC_NIVEL_4', 'PC_NIVEL_5', 'PC_NIVEL_6', 'PC_NIVEL_7', 'PC_NIVEL_8']

## 4. Inventário das bases municipais em CSV

In [5]:
def ler_csv_flexivel(caminho):
    erros = []
    for separador in [",", ";", "\t"]:
        for encoding in ["utf8", "utf8-lossy"]:
            try:
                frame = pl.read_csv(caminho, separator=separador, encoding=encoding, infer_schema_length=10_000)
                if frame.width > 1:
                    return frame
            except Exception as exc:
                erros.append(str(exc))
    raise ValueError(f"Não foi possível ler {caminho.name}. Últimos erros: {erros[-2:]}")

csv_nomes = ["Receitas orçamentárias municipais", "PIB municipal", "Indicador municipal FUNDEB", "Bolsa Família"]
frames_csv, resumo_csv = {}, []
for nome in csv_nomes:
    caminho = localizados[nome]
    if caminho:
        frame = ler_csv_flexivel(caminho); frames_csv[nome] = frame
        resumo_csv.append({"Base": nome, "Arquivo": caminho.name, "Registros": frame.height, "Colunas": frame.width,
                           "Nomes das colunas": ", ".join(frame.columns), "Total de nulos": sum(frame.null_count().row(0))})
display(pl.DataFrame(resumo_csv))
for nome, frame in frames_csv.items():
    print(f"\n### {nome}"); display(frame.head(3)); display(pl.DataFrame({"Coluna": frame.columns, "Tipo Polars": [str(t) for t in frame.dtypes]}))

shape: (4, 6)
┌───────────────────┬───────────────────┬───────────┬─────────┬───────────────────┬────────────────┐
│ Base              ┆ Arquivo           ┆ Registros ┆ Colunas ┆ Nomes das colunas ┆ Total de nulos │
│ ---               ┆ ---               ┆ ---       ┆ ---     ┆ ---               ┆ ---            │
│ str               ┆ str               ┆ i64       ┆ i64     ┆ str               ┆ i64            │
╞═══════════════════╪═══════════════════╪═══════════╪═════════╪═══════════════════╪════════════════╡
│ Receitas          ┆ base_de_dados_mun ┆ 11097     ┆ 4       ┆ ano, sigla_uf,    ┆ 0              │
│ orçamentárias     ┆ icipio_receit…    ┆           ┆         ┆ id_municipio, t…  ┆                │
│ municip…          ┆                   ┆           ┆         ┆                   ┆                │
│ PIB municipal     ┆ base_de_dados_PIB ┆ 11140     ┆ 3       ┆ Ano;UF;Nome       ┆ 11140          │
│                   ┆ _Municipios_2…    ┆           ┆         ┆ UF;Código do      ┆                │
│                   ┆                   ┆           ┆         ┆ Munic…            ┆                │
│ Indicador         ┆ base_dados_fundeb ┆ 11131     ┆ 4       ┆ ano,              ┆ 0              │
│ municipal FUNDEB  ┆ _indicador_mu…    ┆           ┆         ┆ id_municipio,     ┆                │
│                   ┆                   ┆           ┆         ┆ sigla_uf, t…      ┆                │
│ Bolsa Família     ┆ base_dados_bolsa_ ┆ 11140     ┆ 4       ┆ ano_referencia,   ┆ 0              │
│                   ┆ familia_2023_…    ┆           ┆         ┆ id_municipio, …   ┆                │
└───────────────────┴───────────────────┴───────────┴─────────┴───────────────────┴────────────────┘

### Receitas orçamentárias municipais

shape: (3, 4)
┌──────┬──────────┬──────────────┬─────────────┐
│ ano  ┆ sigla_uf ┆ id_municipio ┆ total_valor │
│ ---  ┆ ---      ┆ ---          ┆ ---         │
│ i64  ┆ str      ┆ i64          ┆ f64         │
╞══════╪══════════╪══════════════╪═════════════╡
│ 2023 ┆ AC       ┆ 1200013      ┆ 6.0977e8    │
│ 2023 ┆ AC       ┆ 1200054      ┆ 4.1526e8    │
│ 2023 ┆ AC       ┆ 1200104      ┆ 9.6842e8    │
└──────┴──────────┴──────────────┴─────────────┘

shape: (4, 2)
┌──────────────┬─────────────┐
│ Coluna       ┆ Tipo Polars │
│ ---          ┆ ---         │
│ str          ┆ str         │
╞══════════════╪═════════════╡
│ ano          ┆ Int64       │
│ sigla_uf     ┆ String      │
│ id_municipio ┆ Int64       │
│ total_valor  ┆ Float64     │
└──────────────┴─────────────┘

### PIB municipal

shape: (3, 3)
┌─────────────────────────────────┬─────────────────────────────────┬─────────────────────┐
│ Ano;UF;Nome UF;Código do Munic… ┆  a preços correntes;Produto In… ┆  a preços correntes │
│ ---                             ┆ ---                             ┆ ---                 │
│ str                             ┆ str                             ┆ str                 │
╞═════════════════════════════════╪═════════════════════════════════╪═════════════════════╡
│ 2022;RO;Rondônia;1100015;Alta … ┆ 33                              ┆ null                │
│ 2022;RO;Rondônia;1100023;Ariqu… ┆ 43                              ┆ null                │
│ 2022;RO;Rondônia;1100031;Cabix… ┆ 69                              ┆ null                │
└─────────────────────────────────┴─────────────────────────────────┴─────────────────────┘

shape: (3, 2)
┌─────────────────────────────────┬─────────────┐
│ Coluna                          ┆ Tipo Polars │
│ ---                             ┆ ---         │
│ str                             ┆ str         │
╞═════════════════════════════════╪═════════════╡
│ Ano;UF;Nome UF;Código do Munic… ┆ String      │
│  a preços correntes;Produto In… ┆ String      │
│  a preços correntes             ┆ String      │
└─────────────────────────────────┴─────────────┘

### Indicador municipal FUNDEB

shape: (3, 4)
┌──────┬──────────────┬──────────┬─────────────┐
│ ano  ┆ id_municipio ┆ sigla_uf ┆ total_valor │
│ ---  ┆ ---          ┆ ---      ┆ ---         │
│ i64  ┆ i64          ┆ str      ┆ f64         │
╞══════╪══════════════╪══════════╪═════════════╡
│ 2023 ┆ 1100015      ┆ RO       ┆ 2.6211e8    │
│ 2023 ┆ 1100023      ┆ RO       ┆ 7.1923e8    │
│ 2023 ┆ 1100031      ┆ RO       ┆ 3.7353e7    │
└──────┴──────────────┴──────────┴─────────────┘

shape: (4, 2)
┌──────────────┬─────────────┐
│ Coluna       ┆ Tipo Polars │
│ ---          ┆ ---         │
│ str          ┆ str         │
╞══════════════╪═════════════╡
│ ano          ┆ Int64       │
│ id_municipio ┆ Int64       │
│ sigla_uf     ┆ String      │
│ total_valor  ┆ Float64     │
└──────────────┴─────────────┘

### Bolsa Família

shape: (3, 4)
┌────────────────┬──────────────┬──────────┬─────────────┐
│ ano_referencia ┆ id_municipio ┆ sigla_uf ┆ total_valor │
│ ---            ┆ ---          ┆ ---      ┆ ---         │
│ i64            ┆ i64          ┆ str      ┆ i64         │
╞════════════════╪══════════════╪══════════╪═════════════╡
│ 2023           ┆ 4107124      ┆ PR       ┆ 2181020     │
│ 2023           ┆ 4128625      ┆ PR       ┆ 1808604     │
│ 2023           ┆ 4106605      ┆ PR       ┆ 7961886     │
└────────────────┴──────────────┴──────────┴─────────────┘

shape: (4, 2)
┌────────────────┬─────────────┐
│ Coluna         ┆ Tipo Polars │
│ ---            ┆ ---         │
│ str            ┆ str         │
╞════════════════╪═════════════╡
│ ano_referencia ┆ Int64       │
│ id_municipio   ┆ Int64       │
│ sigla_uf       ┆ String      │
│ total_valor    ┆ Int64       │
└────────────────┴─────────────┘

## 5. Qualidade inicial e chaves candidatas

In [6]:
def resumo_qualidade(frame, nome):
    return [{"Base": nome, "Variável": c, "Tipo": str(frame.schema[c]), "Nulos": frame[c].null_count(),
             "% nulos": round(100 * frame[c].null_count() / frame.height, 2), "Valores distintos": frame[c].n_unique()}
            for c in frame.columns]

qualidade = [linha for nome, frame in frames_csv.items() for linha in resumo_qualidade(frame, nome)]
display(pl.DataFrame(qualidade))
chaves_testar = {"Receitas orçamentárias municipais": ["id_municipio", "ano"], "PIB municipal": ["Código do Município", "Ano"],
                 "Indicador municipal FUNDEB": ["id_municipio", "ano"], "Bolsa Família": ["id_municipio", "ano_referencia"]}
resultado_chaves = []
for nome, cols in chaves_testar.items():
    frame = frames_csv.get(nome)
    if frame is None: continue
    if all(c in frame.columns for c in cols):
        duplicadas = frame.group_by(cols).len().filter(pl.col("len") > 1).select(pl.col("len").sum()).item() or 0
        status = "Sem duplicidades observadas" if duplicadas == 0 else "Requer investigação"
    else:
        duplicadas, status = None, "Nomes das colunas não correspondem; conferir manualmente"
    resultado_chaves.append({"Base": nome, "Chave candidata": " + ".join(cols), "Linhas duplicadas na chave": duplicadas, "Status": status})
display(pl.DataFrame(resultado_chaves))

shape: (15, 6)
┌─────────────────────────┬────────────────────────┬─────────┬───────┬─────────┬───────────────────┐
│ Base                    ┆ Variável               ┆ Tipo    ┆ Nulos ┆ % nulos ┆ Valores distintos │
│ ---                     ┆ ---                    ┆ ---     ┆ ---   ┆ ---     ┆ ---               │
│ str                     ┆ str                    ┆ str     ┆ i64   ┆ f64     ┆ i64               │
╞═════════════════════════╪════════════════════════╪═════════╪═══════╪═════════╪═══════════════════╡
│ Receitas orçamentárias  ┆ ano                    ┆ Int64   ┆ 0     ┆ 0.0     ┆ 2                 │
│ municip…                ┆                        ┆         ┆       ┆         ┆                   │
│ Receitas orçamentárias  ┆ sigla_uf               ┆ String  ┆ 0     ┆ 0.0     ┆ 26                │
│ municip…                ┆                        ┆         ┆       ┆         ┆                   │
│ Receitas orçamentárias  ┆ id_municipio           ┆ Int64   ┆ 0     ┆ 0.0     ┆ 5561              │
│ municip…                ┆                        ┆         ┆       ┆         ┆                   │
│ Receitas orçamentárias  ┆ total_valor            ┆ Float64 ┆ 0     ┆ 0.0     ┆ 11085             │
│ municip…                ┆                        ┆         ┆       ┆         ┆                   │
│ PIB municipal           ┆ Ano;UF;Nome UF;Código  ┆ String  ┆ 0     ┆ 0.0     ┆ 11140             │
│                         ┆ do Munic…              ┆         ┆       ┆         ┆                   │
│ …                       ┆ …                      ┆ …       ┆ …     ┆ …       ┆ …                 │
│ Indicador municipal     ┆ total_valor            ┆ Float64 ┆ 0     ┆ 0.0     ┆ 11131             │
│ FUNDEB                  ┆                        ┆         ┆       ┆         ┆                   │
│ Bolsa Família           ┆ ano_referencia         ┆ Int64   ┆ 0     ┆ 0.0     ┆ 2                 │
│ Bolsa Família           ┆ id_municipio           ┆ Int64   ┆ 0     ┆ 0.0     ┆ 5570              │
│ Bolsa Família           ┆ sigla_uf               ┆ String  ┆ 0     ┆ 0.0     ┆ 27                │
│ Bolsa Família           ┆ total_valor            ┆ Int64   ┆ 0     ┆ 0.0     ┆ 11139             │
└─────────────────────────┴────────────────────────┴─────────┴───────┴─────────┴───────────────────┘

shape: (4, 4)
┌────────────────────────┬────────────────────────┬────────────────────────┬───────────────────────┐
│ Base                   ┆ Chave candidata        ┆ Linhas duplicadas na   ┆ Status                │
│ ---                    ┆ ---                    ┆ chave                  ┆ ---                   │
│ str                    ┆ str                    ┆ ---                    ┆ str                   │
│                        ┆                        ┆ i64                    ┆                       │
╞════════════════════════╪════════════════════════╪════════════════════════╪═══════════════════════╡
│ Receitas orçamentárias ┆ id_municipio + ano     ┆ 0                      ┆ Sem duplicidades      │
│ municip…               ┆                        ┆                        ┆ observadas            │
│ PIB municipal          ┆ Código do Município +  ┆ null                   ┆ Nomes das colunas não │
│                        ┆ Ano                    ┆                        ┆ correspo…             │
│ Indicador municipal    ┆ id_municipio + ano     ┆ 0                      ┆ Sem duplicidades      │
│ FUNDEB                 ┆                        ┆                        ┆ observadas            │
│ Bolsa Família          ┆ id_municipio +         ┆ 0                      ┆ Sem duplicidades      │
│                        ┆ ano_referencia         ┆                        ┆ observadas            │
└────────────────────────┴────────────────────────┴────────────────────────┴───────────────────────┘

## 6. Catálogo das fontes: disponibilidade, finalidade e limites

In [7]:
catalogo_fontes = pl.DataFrame([
    ("ml_aluno", "Base principal", "Aluno/ano conforme auditoria TC3-38", "Fonte e chave já tratadas na auditoria específica", "Não repetir auditoria aqui"),
    ("Censo Escolar 2023", "Microdados da educação básica", "A confirmar por arquivo interno", "ZIP configurado em dados/fontes_originais/complementar; verificar arquivos internos e cobertura", "Inventariar cabeçalhos sem carregar os microdados completos; confirmar granularidade no dicionário"),
    ("INSE 2023 — escolas", "Indicador socioeconômico escolar", "Escola", "Arquivo escolar localizado; verificar campos e cobertura", "Não usar como indicador municipal sem agregação justificada"),
    ("Receitas orçamentárias municipais", "Finanças públicas", "Município/ano provável", "CSV localizado; confirmar definição de total_valor e unidade", "Não integrado"),
    ("Indicador municipal FUNDEB", "Financiamento educacional", "Município/ano provável", "CSV localizado; confirmar o significado de total_valor", "Não assumir que equivale a gasto por aluno sem fórmula"),
    ("PIB municipal", "Contexto econômico", "Município/ano", "CSV localizado; converter valores formatados para número antes de calcular", "Não integrado"),
    ("Bolsa Família", "Transferência de renda", "Município/ano provável", "CSV localizado; confirmar se total_valor é valor, famílias ou beneficiários", "Não chamar de percentual sem denominador"),
    ("INSE 2023 — municípios/estados/Brasil", "Recortes agregados INSE", "Município/UF/Brasil", "Não aparecem na listagem atual de `dados/fontes_originais/complementar`", "Inventariar apenas se o grupo adicionar esses arquivos à pasta"),
    ("CadÚnico, pobreza, IDHM renda e Gini", "Indicadores socioeconômicos planejados", "A confirmar", "Não identificados entre os arquivos complementares inspecionados nesta execução", "Não declarar disponíveis sem arquivo ou fonte validada"),
    ("Siconfi", "Orçamento/despesa em educação", "Município/ano a confirmar", "Não identificado entre os CSVs complementares inspecionados nesta execução", "Não declarar indicador pronto"),
], schema=["Base/fonte", "Finalidade", "Granularidade esperada", "Estado da verificação", "Limite/observação"], orient="row")
display(catalogo_fontes)

shape: (10, 5)
┌───────────────────┬───────────────────┬───────────────────┬───────────────────┬──────────────────┐
│ Base/fonte        ┆ Finalidade        ┆ Granularidade     ┆ Estado da         ┆ Limite/observaçã │
│ ---               ┆ ---               ┆ esperada          ┆ verificação       ┆ o                │
│ str               ┆ str               ┆ ---               ┆ ---               ┆ ---              │
│                   ┆                   ┆ str               ┆ str               ┆ str              │
╞═══════════════════╪═══════════════════╪═══════════════════╪═══════════════════╪══════════════════╡
│ ml_aluno          ┆ Base principal    ┆ Aluno/ano         ┆ Fonte e chave já  ┆ Não repetir      │
│                   ┆                   ┆ conforme          ┆ tratadas na a…    ┆ auditoria aqui   │
│                   ┆                   ┆ auditoria T…      ┆                   ┆                  │
│ Censo Escolar     ┆ Microdados da     ┆ A confirmar por   ┆ ZIP configurado   ┆ Inventariar      │
│ 2023              ┆ educação básica   ┆ arquivo intern…   ┆ em dados/fonte…   ┆ cabeçalhos sem   │
│                   ┆                   ┆                   ┆                   ┆ car…             │
│ INSE 2023 —       ┆ Indicador         ┆ Escola            ┆ Arquivo escolar   ┆ Não usar como    │
│ escolas           ┆ socioeconômico    ┆                   ┆ localizado; ve…   ┆ indicador        │
│                   ┆ escol…            ┆                   ┆                   ┆ munici…          │
│ Receitas          ┆ Finanças públicas ┆ Município/ano     ┆ CSV localizado;   ┆ Não integrado    │
│ orçamentárias     ┆                   ┆ provável          ┆ confirmar defi…   ┆                  │
│ municip…          ┆                   ┆                   ┆                   ┆                  │
│ Indicador         ┆ Financiamento     ┆ Município/ano     ┆ CSV localizado;   ┆ Não assumir que  │
│ municipal FUNDEB  ┆ educacional       ┆ provável          ┆ confirmar o si…   ┆ equivale a gas…  │
│ PIB municipal     ┆ Contexto          ┆ Município/ano     ┆ CSV localizado;   ┆ Não integrado    │
│                   ┆ econômico         ┆                   ┆ converter valo…   ┆                  │
│ Bolsa Família     ┆ Transferência de  ┆ Município/ano     ┆ CSV localizado;   ┆ Não chamar de    │
│                   ┆ renda             ┆ provável          ┆ confirmar se t…   ┆ percentual sem   │
│                   ┆                   ┆                   ┆                   ┆ d…               │
│ INSE 2023 — munic ┆ Recortes          ┆ Município/UF/Bras ┆ Não aparecem na   ┆ Inventariar      │
│ ípios/estados…    ┆ agregados INSE    ┆ il                ┆ listagem atual…   ┆ apenas se o      │
│                   ┆                   ┆                   ┆                   ┆ grupo …          │
│ CadÚnico,         ┆ Indicadores       ┆ A confirmar       ┆ Não identificados ┆ Não declarar     │
│ pobreza, IDHM     ┆ socioeconômicos   ┆                   ┆ entre os arq…     ┆ disponíveis sem  │
│ renda …           ┆ pl…               ┆                   ┆                   ┆ a…               │
│ Siconfi           ┆ Orçamento/despesa ┆ Município/ano a   ┆ Não identificado  ┆ Não declarar     │
│                   ┆ em educação       ┆ confirmar         ┆ entre os CSVs…    ┆ indicador pronto │
└───────────────────┴───────────────────┴───────────────────┴───────────────────┴──────────────────┘

## 7. Variáveis prioritárias — definições que ainda precisam ser fechadas

A lista abaixo registra candidatos mencionados no planejamento. **Não significa que todos estejam disponíveis, calculados ou prontos para uso.** A definição operacional deve ser decidida antes de comparar ou modelar.

In [8]:
variaveis_prioritarias = pl.DataFrame([
    ("gasto_por_aluno_fundeb", "Financiamento educacional", "Definir numerador, denominador, período e população escolar"),
    ("percentual_orcamento_educacao_siconfi", "Finanças públicas", "Definir relatório/conta, numerador e denominador; obter arquivo Siconfi"),
    ("pib_per_capita", "Contexto econômico", "Usar campo per capita do PIB municipal e confirmar ano de referência"),
    ("pobreza", "Contexto socioeconômico", "Definir conceito, população, fonte oficial e ano-base"),
    ("percentual_familias_cadunico", "Vulnerabilidade social", "Definir contagem de famílias e denominador populacional/familiar"),
    ("percentual_bolsa_familia", "Transferência de renda", "Confirmar o que mede total_valor e definir denominador antes de criar percentual"),
    ("idhm_renda", "Desenvolvimento humano", "Confirmar edição, ano-base e disponibilidade municipal"),
    ("indice_gini", "Desigualdade de renda", "Confirmar fonte, escala geográfica, população e ano-base"),
], schema=["Variável candidata", "Categoria", "Definição/validação pendente"], orient="row")
display(variaveis_prioritarias)

shape: (8, 3)
┌─────────────────────────────────┬───────────────────────────┬─────────────────────────────────┐
│ Variável candidata              ┆ Categoria                 ┆ Definição/validação pendente    │
│ ---                             ┆ ---                       ┆ ---                             │
│ str                             ┆ str                       ┆ str                             │
╞═════════════════════════════════╪═══════════════════════════╪═════════════════════════════════╡
│ gasto_por_aluno_fundeb          ┆ Financiamento educacional ┆ Definir numerador, denominador… │
│ percentual_orcamento_educacao_… ┆ Finanças públicas         ┆ Definir relatório/conta, numer… │
│ pib_per_capita                  ┆ Contexto econômico        ┆ Usar campo per capita do PIB m… │
│ pobreza                         ┆ Contexto socioeconômico   ┆ Definir conceito, população, f… │
│ percentual_familias_cadunico    ┆ Vulnerabilidade social    ┆ Definir contagem de famílias e… │
│ percentual_bolsa_familia        ┆ Transferência de renda    ┆ Confirmar o que mede total_val… │
│ idhm_renda                      ┆ Desenvolvimento humano    ┆ Confirmar edição, ano-base e d… │
│ indice_gini                     ┆ Desigualdade de renda     ┆ Confirmar fonte, escala geográ… │
└─────────────────────────────────┴───────────────────────────┴─────────────────────────────────┘

## 8. Regras para integração futura

Antes de fazer qualquer `merge`, validar:

1. **Granularidade:** aluno, escola, município ou UF; não juntar níveis diferentes sem agregação explícita.
2. **Chave:** verificar código oficial, tipo de dado, zeros à esquerda, unicidade e cobertura.
3. **Tempo:** compatibilizar ano da variável com o ano da observação escolar/aluno; não presumir equivalência entre 2023 e 2024.
4. **Semântica:** documentar unidade e significado de `total_valor`; um valor total não é automaticamente percentual nem gasto por aluno.
5. **Cobertura e viés:** quantificar quantas observações ficam sem correspondência e se a ausência é sistemática.
6. **Vazamento de dados:** decidir se a variável estaria disponível no momento em que a previsão seria feita.
7. **Rastreabilidade:** registrar fonte, URL/documentação, data de extração, filtros e transformação aplicada.

O INSE no arquivo de escolas continua sendo uma medida no nível escolar; a presença de código de município serve para identificação/agrupamento e não transforma automaticamente o indicador em medida municipal.

## 10. Inventário padronizado de colunas (todas as fontes localizadas)

Esta seção consolida os metadados em uma única estrutura, mantendo os nomes originais. Quando a descrição, unidade ou granularidade não estiver documentada, o campo ficará como `Não documentado` ou `A confirmar`; não serão inferidos significados como se fossem fatos. Para o Censo em ZIP, a leitura de cabeçalhos é feita sem carregar os microdados completos.

A tabela padrão contém: fonte, arquivo, tabela/aba, nome original da coluna, sigla, descrição, tipo de origem, tipo Python, papel da variável, unidade, granularidade, chave candidata e observações.

In [9]:
import io

COLUNAS_CATALOGO = [
    "fonte", "arquivo", "tabela_aba", "nome_coluna", "sigla", "descricao",
    "tipo_origem", "tipo_python", "papel_variavel", "unidade_medida",
    "granularidade", "chave_candidata", "observacoes"
]
linhas_catalogo = []

def classificar_papel(nome_coluna):
    n = str(nome_coluna).lower()
    if any(t in n for t in ["id_municipio", "co_municipio", "codigo do municipio", "cod_mun"]):
        return "Identificador geográfico"
    if n in {"ano", "ano_referencia", "nu_ano_saeb", "year"} or "ano" in n:
        return "Temporal"
    if n.startswith("pc_nivel_") or "percentual" in n or "per capita" in n:
        return "Indicador/percentual (confirmar unidade)"
    if any(t in n for t in ["valor", "pib", "media", "média", "quantidade", "qtd"]):
        return "Medida numérica (confirmar significado)"
    if n.startswith("tp_") or n.startswith("sg_") or n in {"uf", "nome uf", "nome do município"}:
        return "Categoria/código"
    return "A classificar"

def adicionar_colunas_catalogo(df, fonte, arquivo, tabela_aba, granularidade, descricao_por_coluna=None, tipo_origem_por_coluna=None, observacao=""):
    descricao_por_coluna = descricao_por_coluna or {}
    tipo_origem_por_coluna = tipo_origem_por_coluna or {}
    for col in df.columns:
        nome = str(col)
        linhas_catalogo.append({
            "fonte": fonte, "arquivo": arquivo, "tabela_aba": str(tabela_aba),
            "nome_coluna": nome,
            "sigla": nome if nome.isupper() or "_" in nome else "Não identificada",
            "descricao": descricao_por_coluna.get(nome, "Não documentado no dicionário localizado"),
            "tipo_origem": tipo_origem_por_coluna.get(nome, "Não identificado"),
            "tipo_python": str(df[col].dtype) if hasattr(df, "dtypes") and col in getattr(df, "columns", []) else "Não carregado (somente cabeçalho)",
            "papel_variavel": classificar_papel(nome),
            "unidade_medida": "A confirmar na documentação da fonte",
            "granularidade": granularidade,
            "chave_candidata": "Candidata; validar unicidade e cobertura" if any(t in nome.lower() for t in ["id_municipio", "co_municipio", "ano", "codigo do municipio"]) else "Não avaliada",
            "observacoes": observacao
        })

# A) CSVs municipais já carregados na seção 4
for nome, df in frames_csv.items():
    caminho = localizados.get(nome)
    adicionar_colunas_catalogo(df, nome, caminho.name if caminho else "Não localizado", "CSV", "Município/ano provável; confirmar no dicionário", observacao="Tipo Python reflete a leitura atual; verificar conversões de moeda/decimal.")

# B) Todas as guias das planilhas INSE localizadas
for nome, guias in amostras_inse.items():
    caminho = localizados.get(nome)
    for aba, df_aba in guias.items():
        granularidade = "Escola" if "escola" in nome.lower() else ("Município" if "município" in nome.lower() else "UF/Brasil ou a confirmar")
        adicionar_colunas_catalogo(df_aba, nome, caminho.name if caminho else "Não localizado", aba, granularidade, observacao="Consultar a guia Dicionário para validar descrição e significado dos campos.")

# C) Censo Escolar: inventariar cabeçalhos dos CSVs dentro do ZIP, sem carregar os registros.
censo_cabecalhos = []
if caminho_censo_zip:
    try:
        with zipfile.ZipFile(caminho_censo_zip, "r") as zf:
            candidatos_csv = [n for n in zf.namelist() if n.lower().endswith(".csv") and not n.endswith("/")]
            print(f"Arquivos CSV encontrados no ZIP do Censo: {len(candidatos_csv)}")
            for nome_interno in candidatos_csv:
                try:
                    with zf.open(nome_interno) as arq:
                        conteudo = arq.read(1024 * 1024)
                        cabecalho = None
                        ultimo_erro = None
                        for enc in ["utf-8-sig", "latin1"]:
                            try:
                                texto = conteudo.decode(enc)
                                cabecalho = pl.read_csv(io.StringIO(texto), separator=";", n_rows=0)
                                if len(cabecalho.columns) <= 1:
                                    cabecalho = pl.read_csv(io.StringIO(texto), separator=",", n_rows=0)
                                break
                            except Exception as exc:
                                ultimo_erro = exc
                        if cabecalho is None:
                            raise ultimo_erro or ValueError("Cabeçalho não lido")
                    df_cabecalho = pl.DataFrame(schema={col: pl.String for col in cabecalho.columns})
                    adicionar_colunas_catalogo(
                        df_cabecalho, "Censo Escolar 2023", caminho_censo_zip.name,
                        nome_interno, "A confirmar pelo arquivo/dicionário",
                        observacao="Inventário de cabeçalho; microdados completos não foram carregados. Confirmar descrição e granularidade no dicionário oficial."
                    )
                    censo_cabecalhos.append({"arquivo_interno": nome_interno, "quantidade_colunas": len(cabecalho.columns), "status": "Cabeçalho lido"})
                except Exception as exc:
                    censo_cabecalhos.append({"arquivo_interno": nome_interno, "quantidade_colunas": None, "status": f"Cabeçalho não lido: {exc}"})
        display(pl.DataFrame(censo_cabecalhos))
    except Exception as exc:
        print("Falha ao processar o ZIP do Censo:", exc)
else:
    print("Censo Escolar: inventário de colunas pendente porque o ZIP não foi localizado.")

# D) Base consolidada do grupo: inventariar apenas se o arquivo for localizado automaticamente
resumo_consolidado = []
for caminho in consolidados_encontrados:
    try:
        if caminho.suffix.lower() == ".csv":
            df_con = ler_csv_flexivel(caminho).head(1000)
            fonte_con = "Base consolidada do grupo (amostra de até 1.000 linhas)"
            adicionar_colunas_catalogo(df_con, fonte_con, caminho.name, "CSV consolidado", "Conforme documentação da consolidação", observacao="Tipo Python e exemplos derivados de amostra; confirmar filtros e regras usados pelo responsável.")
        elif caminho.suffix.lower() in {".xlsx", ".xls"}:
            planilhas = pl.read_excel(caminho, sheet_id=0, engine="openpyxl")
            for aba, df_con in planilhas.items():
                df_con = df_con.head(1000)
                adicionar_colunas_catalogo(df_con, "Base consolidada do grupo (amostra de até 1.000 linhas)", caminho.name, aba, "Conforme documentação da consolidação", observacao="Confirmar filtros, período, granularidade e critérios com o responsável.")
        elif caminho.suffix.lower() == ".parquet":
            try:
                import pyarrow.parquet as pq
                schema = pq.read_schema(caminho)
                df_schema = pl.DataFrame(schema={c: pl.String for c in schema.names})
                adicionar_colunas_catalogo(df_schema, "Base consolidada do grupo (schema Parquet)", caminho.name, "Parquet", "Conforme documentação da consolidação", observacao="Somente schema; confirmar filtros e critérios com o responsável.")
            except Exception as exc:
                resumo_consolidado.append({"arquivo": caminho.name, "status": f"Schema Parquet não lido: {exc}"})
        else:
            resumo_consolidado.append({"arquivo": caminho.name, "status": "Formato encontrado, leitura não implementada nesta seção"})
        resumo_consolidado.append({"arquivo": caminho.name, "status": "Colunas adicionadas ao catálogo; critérios ainda precisam ser documentados"})
    except Exception as exc:
        resumo_consolidado.append({"arquivo": caminho.name, "status": f"Erro de leitura: {exc}"})
if resumo_consolidado:
    display(pl.DataFrame(resumo_consolidado))
else:
    print("Nenhuma base com consolid no nome foi localizada. Confirmar o nome/caminho com o grupo antes de inventariá-la.")

# Tabela final padronizada
catalogo_colunas = pl.DataFrame(linhas_catalogo, schema=COLUNAS_CATALOGO, orient="row")
if not catalogo_colunas.is_empty():
    catalogo_colunas = catalogo_colunas.unique(subset=["fonte", "arquivo", "tabela_aba", "nome_coluna"], maintain_order=True)
    display(catalogo_colunas)
    print("Resumo por fonte:")
    display(catalogo_colunas.group_by(["fonte", "arquivo", "tabela_aba"], maintain_order=True).agg(pl.col("nome_coluna").n_unique().alias("quantidade_colunas")))
    # Exportação para revisão da equipe; o arquivo é gerado na raiz do repositório.
    caminho_saida = RESULTADOS_TABELAS_DIR / "inventario_padronizado_bases_complementares.csv"
    caminho_saida.parent.mkdir(parents=True, exist_ok=True)
    catalogo_colunas.write_csv(caminho_saida, include_bom=True)
    print(f"Inventário exportado para: {caminho_saida.relative_to(PROJECT_ROOT)}")
else:
    print("Nenhuma coluna foi inventariada. Confira os caminhos e a leitura das fontes.")

Arquivos CSV encontrados no ZIP do Censo: 1

shape: (1, 3)
┌───────────────────────────────┬────────────────────┬────────────────┐
│ arquivo_interno               ┆ quantidade_colunas ┆ status         │
│ ---                           ┆ ---                ┆ ---            │
│ str                           ┆ i64                ┆ str            │
╞═══════════════════════════════╪════════════════════╪════════════════╡
│ microdados_ed_basica_2023.csv ┆ 408                ┆ Cabeçalho lido │
└───────────────────────────────┴────────────────────┴────────────────┘

Nenhuma base com consolid no nome foi localizada. Confirmar o nome/caminho com o grupo antes de inventariá-la.

shape: (447, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ fonte     ┆ arquivo   ┆ tabela_ab ┆ nome_colu ┆ … ┆ unidade_m ┆ granulari ┆ chave_can ┆ observac │
│ ---       ┆ ---       ┆ a         ┆ na        ┆   ┆ edida     ┆ dade      ┆ didata    ┆ oes      │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Receitas  ┆ base_de_d ┆ CSV       ┆ ano       ┆ … ┆ A         ┆ Município ┆ Candidata ┆ Tipo     │
│ orçamentá ┆ ados_muni ┆           ┆           ┆   ┆ confirmar ┆ /ano      ┆ ; validar ┆ Python   │
│ rias      ┆ cipio_rec ┆           ┆           ┆   ┆ na docume ┆ provável; ┆ unicidade ┆ reflete  │
│ municip…  ┆ eit…      ┆           ┆           ┆   ┆ ntação    ┆ confir…   ┆ e…        ┆ a        │
│           ┆           ┆           ┆           ┆   ┆ da…       ┆           ┆           ┆ leitura  │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ Receitas  ┆ base_de_d ┆ CSV       ┆ sigla_uf  ┆ … ┆ A         ┆ Município ┆ Não       ┆ Tipo     │
│ orçamentá ┆ ados_muni ┆           ┆           ┆   ┆ confirmar ┆ /ano      ┆ avaliada  ┆ Python   │
│ rias      ┆ cipio_rec ┆           ┆           ┆   ┆ na docume ┆ provável; ┆           ┆ reflete  │
│ municip…  ┆ eit…      ┆           ┆           ┆   ┆ ntação    ┆ confir…   ┆           ┆ a        │
│           ┆           ┆           ┆           ┆   ┆ da…       ┆           ┆           ┆ leitura  │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ Receitas  ┆ base_de_d ┆ CSV       ┆ id_munici ┆ … ┆ A         ┆ Município ┆ Candidata ┆ Tipo     │
│ orçamentá ┆ ados_muni ┆           ┆ pio       ┆   ┆ confirmar ┆ /ano      ┆ ; validar ┆ Python   │
│ rias      ┆ cipio_rec ┆           ┆           ┆   ┆ na docume ┆ provável; ┆ unicidade ┆ reflete  │
│ municip…  ┆ eit…      ┆           ┆           ┆   ┆ ntação    ┆ confir…   ┆ e…        ┆ a        │
│           ┆           ┆           ┆           ┆   ┆ da…       ┆           ┆           ┆ leitura  │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ Receitas  ┆ base_de_d ┆ CSV       ┆ total_val ┆ … ┆ A         ┆ Município ┆ Não       ┆ Tipo     │
│ orçamentá ┆ ados_muni ┆           ┆ or        ┆   ┆ confirmar ┆ /ano      ┆ avaliada  ┆ Python   │
│ rias      ┆ cipio_rec ┆           ┆           ┆   ┆ na docume ┆ provável; ┆           ┆ reflete  │
│ municip…  ┆ eit…      ┆           ┆           ┆   ┆ ntação    ┆ confir…   ┆           ┆ a        │
│           ┆           ┆           ┆           ┆   ┆ da…       ┆           ┆           ┆ leitura  │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ PIB       ┆ base_de_d ┆ CSV       ┆ Ano;UF;No ┆ … ┆ A         ┆ Município ┆ Candidata ┆ Tipo     │
│ municipal ┆ ados_PIB_ ┆           ┆ me        ┆   ┆ confirmar ┆ /ano      ┆ ; validar ┆ Python   │
│           ┆ Municipio ┆           ┆ UF;Código ┆   ┆ na docume ┆ provável; ┆ unicidade ┆ reflete  │
│           ┆ s_2…      ┆           ┆ do Munic… ┆   ┆ ntação    ┆ confir…   ┆ e…        ┆ a        │
│           ┆           ┆           ┆           ┆   ┆ da…       ┆           ┆           ┆ leitura  │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Censo     ┆ microdado ┆ microdado ┆ QT_TUR_IN ┆ … ┆ A         ┆ A         ┆ Não       ┆ Inventár │
│ Escolar   ┆ s_ed_basi ┆ s_ed_basi ┆ F_PRE_INT ┆   ┆ confirmar ┆ confirmar ┆ avaliada  ┆ io de    │
│ 2023      ┆ ca_2023.z ┆ ca_2023.c ┆           ┆   ┆ na docume ┆ pelo arqu ┆           ┆ cabeçalh │
│           ┆ ip        ┆ sv        ┆           ┆   ┆ ntação    ┆ ivo/dicio ┆           ┆ o;       │
│           ┆           ┆           ┆           ┆   ┆ da…       ┆ …         ┆           ┆ micro…   │
│ Censo     ┆ microdado ┆ microdado ┆ QT_TUR_FU ┆ … ┆ A         ┆ A         ┆ Não       ┆ Inventár │
│ Escolar   ┆ s_ed_basi ┆ s_ed_basi ┆ ND_INT    ┆   ┆ confirmar ┆ confirmar ┆ avaliada  ┆ io de    │
│ 2023      ┆ ca_2023.z ┆ ca_2023.c ┆           ┆   ┆ na docume ┆ pelo arqu ┆           ┆ cabeçalh │
│           ┆ ip        ┆ sv        ┆           ┆   ┆ ntação    ┆ ivo/dicio ┆           ┆ o;       │
│           ┆           ┆           ┆           ┆   ┆ da…       ┆ …         ┆           ┆ micro…   │
│ Censo     ┆ microdado ┆ microdado ┆ QT_TUR_FU ┆ … ┆ A         ┆ A         ┆ Não       ┆ Inventár │
│ Escolar   ┆ s_ed_basi ┆ s_ed_basi ┆ ND_AI_INT ┆   ┆ confirmar ┆ confirmar ┆ avaliada  ┆ io de    │
│ 2023      ┆ ca_2023.z ┆ ca_2023.c ┆           ┆   ┆ na docume ┆ pelo arqu ┆           ┆ cabeçalh │
│           ┆ ip        ┆ sv        ┆           ┆   ┆ ntação    ┆ ivo/dicio ┆           ┆ o;       │
│           ┆           ┆           ┆           ┆   ┆ da…       ┆ …         ┆           ┆ micro…   │
│ Censo     ┆ microdado ┆ microdado ┆ QT_TUR_FU ┆ … ┆ A         ┆ A         ┆ Não       ┆ Inventár │
│ Escolar   ┆ s_ed_basi ┆ s_ed_basi ┆ ND_AF_INT ┆   ┆ confirmar ┆ confirmar ┆ avaliada  ┆ io de    │
│ 2023      ┆ ca_2023.z ┆ ca_2023.c ┆           ┆   ┆ na docume ┆ pelo arqu ┆           ┆ cabeçalh │
│           ┆ ip        ┆ sv        ┆           ┆   ┆ ntação    ┆ ivo/dicio ┆           ┆ o;       │
│           ┆           ┆           ┆           ┆   ┆ da…       ┆ …         ┆           ┆ micro…   │
│ Censo     ┆ microdado ┆ microdado ┆ QT_TUR_ME ┆ … ┆ A         ┆ A         ┆ Não       ┆ Inventár │
│ Escolar   ┆ s_ed_basi ┆ s_ed_basi ┆ D_INT     ┆   ┆ confirmar ┆ confirmar ┆ avaliada  ┆ io de    │
│ 2023      ┆ ca_2023.z ┆ ca_2023.c ┆           ┆   ┆ na docume ┆ pelo arqu ┆           ┆ cabeçalh │
│           ┆ ip        ┆ sv        ┆           ┆   ┆ ntação    ┆ ivo/dicio ┆           ┆ o;       │
│           ┆           ┆           ┆           ┆   ┆ da…       ┆ …         ┆           ┆ micro…   │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

Resumo por fonte:

shape: (7, 4)
┌─────────────────────────┬─────────────────────────┬─────────────────────────┬────────────────────┐
│ fonte                   ┆ arquivo                 ┆ tabela_aba              ┆ quantidade_colunas │
│ ---                     ┆ ---                     ┆ ---                     ┆ ---                │
│ str                     ┆ str                     ┆ str                     ┆ u32                │
╞═════════════════════════╪═════════════════════════╪═════════════════════════╪════════════════════╡
│ Receitas orçamentárias  ┆ base_de_dados_municipio ┆ CSV                     ┆ 4                  │
│ municip…                ┆ _receit…                ┆                         ┆                    │
│ PIB municipal           ┆ base_de_dados_PIB_Munic ┆ CSV                     ┆ 3                  │
│                         ┆ ipios_2…                ┆                         ┆                    │
│ Indicador municipal     ┆ base_dados_fundeb_indic ┆ CSV                     ┆ 4                  │
│ FUNDEB                  ┆ ador_mu…                ┆                         ┆                    │
│ Bolsa Família           ┆ base_dados_bolsa_famili ┆ CSV                     ┆ 4                  │
│                         ┆ a_2023_…                ┆                         ┆                    │
│ INSE 2023 — escolas     ┆ INSE_2023_escolas.xlsx  ┆ INSE_ESC_2023           ┆ 22                 │
│ INSE 2023 — escolas     ┆ INSE_2023_escolas.xlsx  ┆ Dicionário              ┆ 2                  │
│ Censo Escolar 2023      ┆ microdados_ed_basica_20 ┆ microdados_ed_basica_20 ┆ 408                │
│                         ┆ 23.zip                  ┆ 23.csv                  ┆                    │
└─────────────────────────┴─────────────────────────┴─────────────────────────┴────────────────────┘

Inventário exportado para: resultados/tabelas/inventario_padronizado_bases_complementares.csv

## 11. Registro da base consolidada e justificativa dos filtros

A existência de uma base consolidada preparada por Mauricio deve ser documentada separadamente do inventário das fontes originais. Antes de justificar a seleção, registrar com o responsável: (1) nome e caminho exatos do arquivo; (2) fontes de origem; (3) período de cada fonte; (4) filtros aplicados e respectivos critérios; (5) colunas mantidas/removidas e justificativa; (6) granularidade e chaves; (7) quantidade de registros antes e depois de cada filtro; (8) limitações de cobertura, incluindo a ausência observada de municípios paulistas na tabela `alunos` de 2023 consultada pelo grupo.

**Não preencher por suposição:** enquanto os critérios não forem confirmados, a escolha das variáveis e os filtros da base consolidada devem constar como `A confirmar com o responsável`. A tabela gerada pelo código acima cataloga estrutura e tipos; não comprova a justificativa metodológica da seleção.

## 12. Checklist antes de considerar o inventário concluído

- [ ] Confirmar com o grupo quais bases realmente serão utilizadas.
- [ ] Confirmar o caminho exato e a versão da base consolidada preparada por Mauricio.
- [ ] Documentar os filtros e a quantidade de registros antes/depois.
- [ ] Revisar as descrições com os dicionários oficiais; não tratar classificações automáticas como documentação oficial.
- [ ] Validar granularidade, período, chaves candidatas e cobertura de cada fonte.
- [ ] Registrar arquivos não encontrados como pendentes, não como dados disponíveis.
- [ ] Manter integração e seleção final de features fora do escopo do TC3-40.

## 13. Conclusão técnica

Este notebook registra a disponibilidade, a estrutura e o inventário padronizado das colunas encontradas, além de destacar verificações pendentes. Os resultados de inventário **não comprovam validade substantiva dos indicadores nem compatibilidade entre fontes**.

- A `ml_aluno` permanece como base principal, com auditoria documentada no TC3-38.
- O INSE escolar deve ser validado no nível de escola antes de qualquer junção. O ZIP dos microdados do Censo Escolar é inventariado separadamente do dicionário; os cabeçalhos internos são lidos sem carregar a base completa.
- As bases municipais de receitas, FUNDEB, PIB e Bolsa Família podem ser catalogadas, mas suas definições, unidades, períodos e chaves precisam ser confirmados.
- Fontes ou indicadores não encontrados nesta execução permanecem pendentes; não serão tratados como dados disponíveis.
- A integração e a criação de features ficam para uma etapa posterior, com decisões documentadas e testes reproduzíveis.
- A tabela `catalogo_colunas` padroniza metadados, mas descrições/unidades não documentadas precisam ser conferidas em fontes oficiais.
- A base consolidada e seus filtros só poderão ser justificados após confirmação dos critérios e da versão com o responsável.
- A lista definitiva de fontes deve ser ajustada após confirmação da agenda do grupo.